sudo: required 
services: 
  - docker
  
before_install: 
  - docker build -t hdelas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hdelas/docker-react npm run test -- --coverage

language: generic 

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-eu-west-3-647612158770
  bucket_path: "docker"
    
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY